#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 30 14:48:25 2019

@author: AFS
"""

import glob, collections

list_username = []
out = []

#sorted(glob.glob)
files = sorted(glob.glob("/home/perrot/Documents/Projet4/data_course-v1_CNAM+01032+session01/*"))

for file in files:
    with open(file,'r') as f:
        s = f.read().strip()
        l = eval(s)
        
        try:
            username = l["content"]["username"]
        except:
            pass
        list_username.append(username)
        
