#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 21 09:21:03 2019

@author: oem
"""

import py7zlib
filename = "/home/oem/Desktop/projet_mooc/archives_mooc/CNAM_01002_Trimestre_1_2014.7z"
content=open(filename,"rb")
archive = py7zlib.Archive7z(content)
data = archive.getmember(archive.getnames()[0]).read()


from pyunpack import Archive
filename = "/home/oem/Desktop/projet_mooc/archives_mooc/CNAM_01002_Trimestre_1_2014.7z"
Archive(filename).extractall("<output path>")

import py7zlib
f7file = "<mypath>/boost_1_60_0.7z"
with open(f7file, 'rb') as f:
     z = py7zlib.Archive7z(f)
     z.list()
     
   
import lzma
lzma.open('home/oem/Desktop/projet_mooc/archives_mooc/CNAM_01002_Trimestre_1_2014.7z')
    f.extractall(r"<output path>")
    
"""    
import subprocess
filename = "/home/oem/Desktop/projet_mooc/archives_mooc/CNAM_01002_Trimestre_1_2014.7z"
subprocess.Popen(zip_exe+' x '+filename+' -o'+output_loc,stdout=subprocess.PIPE)
"""





import libarchive
import json
import pprint
import ast
filename = "/home/oem/Desktop/projet_mooc/archives_mooc/CNAM_01002_Trimestre_1_2014.7z"

#Pour extraire une archive dans le répertoire actuel:
extract_7z = libarchive.extract_file(filename)

#Pour lire une archive:
with libarchive.file_reader(filename) as archive:
     
         for entry in archive:
             #print(entry)
             concate = b"" #encore en binaire
             for block in entry.get_blocks():
                 concate = concate+block
             #archive.write(block)
             print(concate)  
             encoded = concate.decode('utf-8')
             json7zip = ast.literal_eval(encoded)
             pprint.pprint(json7zip)
     
            
            
            
            
      
        
        
        
        
        
        
        
        

   











     
        
        
        
        
        
        
"""     
        
import libarchive.public

with libarchive.file_reader('filename') as archive:
    for entry in e:
        with open('/tmp/' + str(entry), 'wb') as f:
            for block in entry.get_blocks():
                f.write(block)
                
                
            
with libarchive.file_reader(archive) as septzip:
            try:
            
                for entry in septzip:
                    #print(entry)
                    concate = b""
                    for block in entry.get_blocks():
                        concate = concate+block
                        
                    encoded = concate.decode('utf-8')
                    json7zip = ast.literal_eval(encoded)
                    #print(concate)    
                    pprint.pprint(json7zip)#[10]
            except:
                    print('erreur_7zip')                
                
"""               
                
                
                
                
                